### ISSUE TITLE
Apache FOP 2.4?

### ISSUE THREAD

**Issue by ronaldtse** [geraldcombs/chocolatey-packages#1]
Hi @geraldcombs , thank you for making Apache FOP available on Chocolatey!

Any plans to update the Chocolatey package for Apache FOP to 2.4?

Thanks!

**Comment by geraldcombs** [comment]
Done in 2020, although downloads broke at some point. See #2 for details.

**Comment by ronaldtse** [comment]
Thanks @geraldcombs !
